// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UninstallUI
{
    using System.CodeDom.Compiler;
    using System.Drawing;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;


    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// delete configuration
        /// </summary>
        public void PressYesButton()
        {
            #region Variable Declarations
            WpfButton uIYesButton = this.UITemasoftFileMonitorSWindow.UIYesButton;
            #endregion

            // Click 'Yes' button
            Mouse.Click(uIYesButton, new Point(34, 4));
        }
        
        #region Properties
        public UITemasoftFileMonitorSWindow UITemasoftFileMonitorSWindow
        {
            get
            {
                if ((this.mUITemasoftFileMonitorSWindow == null))
                {
                    this.mUITemasoftFileMonitorSWindow = new UITemasoftFileMonitorSWindow();
                }
                return this.mUITemasoftFileMonitorSWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITemasoftFileMonitorSWindow mUITemasoftFileMonitorSWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITemasoftFileMonitorSWindow : WpfWindow
    {
        
        public UITemasoftFileMonitorSWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Temasoft FileMonitor Server";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Temasoft FileMonitor Server");
            #endregion
        }
        
        #region Properties
        public WpfButton UIYesButton
        {
            get
            {
                if ((this.mUIYesButton == null))
                {
                    this.mUIYesButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIYesButton.SearchProperties[WpfButton.PropertyNames.Name] = "Yes";
                    this.mUIYesButton.WindowTitles.Add("Temasoft FileMonitor Server");
                    #endregion
                }
                return this.mUIYesButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIYesButton;
        #endregion
    }
}
